### PR TITLE
Fix getPermissions(), add tests

### PR DESCRIPTION
**Pull request by dmitrizagidulin**
Fixes issue #5.

* Fix PermissionSet constructor signature in getPermissions()
* Add unit tests for getPermissions() and clearPermissions()

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Tagging @dan-f or @nicola or @deiu for review.

**Comment by dmitrizagidulin** [comment]
(Er, in progress, fixing an issue)

**Comment by dmitrizagidulin** [comment]
This PR depends on upstream fix https://github.com/solid/solid-web-client/pull/3

**Comment by dmitrizagidulin** [comment]
Ok, upstream issue fixed, this PR is ready for review.

**Comment by deiu** [comment]
👍 for me.

**Pull request merged**
